name: Release to Beta
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-beta*'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha*'

jobs:
  beta-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Update VERSION file
        run: |
          echo "${{ steps.get_version.outputs.VERSION }}" > VERSION
          
      - name: Update script version
        run: |
          sed -i "s/CURRENT_VERSION=\".*\"/CURRENT_VERSION=\"${{ steps.get_version.outputs.VERSION }}\"/" PVE-Tools.sh
          
      - name: Commit version changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION PVE-Tools.sh
          git commit -m "chore: update beta version to ${{ steps.get_version.outputs.VERSION }}" || echo "No changes to commit"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: beta
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Beta Release ${{ github.ref }}
          body: |
            ## Beta 版本 ${{ steps.get_version.outputs.VERSION }}
            
            ⚠️ 这是测试版本，可能存在不稳定因素，请勿在生产环境使用
            
            ## 安装方式
            
            ```bash
            bash <(curl -sSL https://github.com/Mapleawaa/PVE-Tools-9/blob/beta/PVE-Tools.sh)
            ```
          draft: false
          prerelease: true